export default {
  login: "nciampelletti",
  id: 103954578,
  node_id: "U_kgDOBjI4kg",
  avatar_url: "https://avatars.githubusercontent.com/u/103954578?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/nciampelletti",
  html_url: "https://github.com/nciampelletti",
  followers_url: "https://api.github.com/users/nciampelletti/followers",
  following_url:
    "https://api.github.com/users/nciampelletti/following{/other_user}",
  gists_url: "https://api.github.com/users/nciampelletti/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/nciampelletti/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/nciampelletti/subscriptions",
  organizations_url: "https://api.github.com/users/nciampelletti/orgs",
  repos_url: "https://api.github.com/users/nciampelletti/repos",
  events_url: "https://api.github.com/users/nciampelletti/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/nciampelletti/received_events",
  type: "User",
  site_admin: false,
  name: "Natalia Ciampelletti",
  company: null,
  blog: "",
  location: "Coquitlam",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 4,
  public_gists: 0,
  followers: 0,
  following: 3,
  created_at: "2022-04-18T16:57:49Z",
  updated_at: "2022-05-03T18:49:00Z",
}
